### PR TITLE
Capital H for GitHub

### PR DESCRIPTION
**Pull request by sadikkuzu**

### CODE REVIEW

**Comment by janober** [comment]
Uh, thanks! Wonder how long it takes till all my typos and mistakes got fixed ;-)

**Comment by janober** [comment]
Ah did not see it was on the website. Sorry, that one is not in use anymore. It was just a temporary website before I had the current one in place. I wanted to remove the repository but forgot. Now leave it here for now because of the "open source" issues.

**Comment by sadikkuzu** [comment]
Oh, ok. There are also some typos here: https://n8n.io/contribute 
Happy coding!

**Comment by janober** [comment]
Uh ;-) Can you please send them to jan@n8n.io that I can fix them with the next website-release. Thanks a lot!

**Pull request merged**
